app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
 

Route::get('/', function () {
    return view('auth/login');
});


//RUTA PARA LA GUARDAR FOTOS DEL VEHICULO  
Route::resource('fotocar','FotoCarController');

Route::post('/subir/{id}/{placa}/{cliente}', 'FotoCarController@subir')->name('fotocar.subir');

Route::get('/acerca', function () {
    return view('acerca');
});
 
 
/*LOGIN // NUEVO CLIENTE FRONTEND*/
//Route::get('ventas/creacion', 'Ventas2Controller@create')->name('ventas.create');
Route::get('front/nuevo-cliente', 'FrontEndController@create')->name('nuevo.cliente');
Route::post('/store/sales', 'SalesOrderController@store');

//FIN LOGIN
 
// 

//MODULO DE GESTION DE CITAS ATENCION VEHICULAR
 
/*Ruta para guardar la recepcion de cita */
Route::resource('appointment/receipt','AppointmentController@receipt_cita');
 
 
Route::get('mkt/{cita_id}/pdf', 'AppointmentController@cita_cliente')->name('cita_customer');
 
//FIN MODULO GESTION DE CITAS ATENCION VEHICULAR

// 
//ASESOR : RECEPCION
//Route::resource('asesor/inventario','RecepcionAsesorController');
 
  
Route::auth();

   

/**--------- reportes */
 


// ----------------------------------------------------------------------------------


//FIN RECEPCION OC

 
//fin PARAMETROS  DE SUCURSAL


// Inicio Seguridad-Sucursal
  
//++INICIO RECEPCIONES
 
//FIN RECEPCIONES

 
/*** RUTAS PARA COTIZACIÓN*/
 

//Vehiculos - RT 
//FIN Tipo de Transacciones
 
//FIN TRX VARIAS
 
// FIN ITEM-MMA

//IMPORTACION DE REGISTROS
 
//FIN //IMPORTACION DE REGISTROS


// organizacion

Route::get('/home', 'HomeController@index');
 
Route::get('/home', 'HomeController@index');


// fndlookup 
 
// labor
 
Route::get('/{slug?}', 'HomeController@index');
 
//CREACION AUTOMATICA DE ORDEN DE TRABAJO
Route::resource('asesor/vehiculo','VehiculoController');


Route::resource('ventas/cliente','ClienteController');
 
Route::resource('seguridad/usuario','UsuarioController');
 
Route::resource('appointment/receipt','AppointmentController@receipt_cita');

Route::get('/subir', function(){
	return "hola mundo";
});



  

app/Http/Controllers/FrontEndController.php
<?php

namespace sisVentas\Http\Controllers;

use Illuminate\Http\Request;

use sisVentas\WfNotifications;
use sisVentas\Http\Requests;
use sisVentas\FsetupReminder;
use Laracasts\Flash\Flash;
use Mail;
use Auth;
use Session;
use sisVentas\Site;

class FrontEndController extends Controller
{		
		public function create()
		{
			 
			return view('frontend.register.new') ;
		}
    
	     public function enviarmail(Request $req)
	     {
                 $data = $req->all();
                 $user = FsetupReminder::all();

                 
                 $separador = ","; 
                 $mi_cadena = $user[0]->cc;

                 $array = explode($separador,$mi_cadena); 
             
           $correo = $req->input('x');
           $c1 = $user[0]->correode;
          // return $c1;

            Mail::send('email.message', ['user' => $user], function ($m) use ($user, $correo, $array) {
                $m->from($user[0]->correode, 'Your Application');
    
                $m->to($correo)->cc($array)->subject($user[0]->asunto);
                
            });
            
            

         }


    public function sendMailToVendor(Request $req)
     {
             $data = $req->all();

            dd($data);
             $user = FsetupReminder::all();
             $name = "recepcion_" .$recepcionid.".pdf";
             $ruta = asset("uploads/public/pdf/". $name); //"storage/public/pdf/recepcion_" 
             
             $separador = ","; 
             $mi_cadena = $user[0]->cc;

             $array = explode($separador,$mi_cadena); 
         
		   $correo = $req->input('x');
		   $c1 = $user[0]->correode;
		  // return $c1;

			Mail::send('email.message', ['user' => $user], function ($m) use ($user, $correo, $array) {
				$m->from($user[0]->correode, 'Your Application');

				$m->to($correo); //->cc($array)
				$m->subject($user[0]->asunto);
				$m->attach($ruta, [
					'as' => $name,
					'mime' => 'application/pdf'
					]);
            
        });
         

     }
 
         public function store2(Request $r)
         {
                dd($r);
             $savemail = new FsetupReminder();
             $savemail->mailto = $r->input('mailto');
             $savemail->cc = $r->input('cc');
             $savemail->message = $r->input('message');
             $savemail->description_use = $r->input('description_use');
             $savemail->module = $r->input('module');
             $savemail->subject = $r->input('subject');
             $savemail->due_days = $r->input('due_days');
            // $savemail->site_id = Session::get('site_id'); 
             $savemail->created_by = Auth::user()->id;
             $savemail->last_updated_by = Auth::user()->id;

             //return $savemail;

             $savemail->save();

             Flash::success("Se ha registrado de manera exitosa!")->important();

             return redirect()->route('configuracion.correo.index');


         }
 

         public function index()
         {
             $data = FsetupReminder::all();

            return view('configuracion.correos.index', compact('data'));
         }

         public function edit($id)
         {
              $edit = FsetupReminder::find($id);
               $sucursales = Site::select('name', 'id')->where('condicion','=', 1)->orderBy('name', 'ASC')->get();

               //dd( $edit);
              return view('configuracion.correos.edit', compact('edit','sucursales'));
 
         }

          public function edittest($id)
         {
              $edit = FsetupReminder::find($id);
               
              return view('configuracion.correostest.edit', compact('edit' ));
 
         }

         public function update(Request $r, $id)
         {
               // dd($r);
             $savemail = FsetupReminder::find($id);
             $savemail->mailto = $r->input('mailto');
             $savemail->cc = $r->input('cc');
             $savemail->message = $r->input('message');
             $savemail->description_use = $r->input('description_use');
             $savemail->module = $r->input('module');
             $savemail->subject = $r->input('subject');
             $savemail->due_days = $r->input('due_days');
            
             $savemail->last_updated_by = Auth::user()->id;

          // dd( $savemail);

            //return $savemail;

            $savemail->save();

            Flash::success("Se ha actualizado de manera exitosa!")->important();

            return redirect()->route('configuracion.correo.index');
         }



}

resources/views/frontend/register/new.blade.php
@extends('layouts.app')
 
@section('content')
<style>
    body {
        font-size: 14px !important;
        font-family: Arial, Helvetica, sans-serif;
        margin: 0px 0px 10px 0px;
        padding: 0px;
        background: #FFF;
        color: #666666;
    }

   
    .MainArea {
        margin-left: auto;
        margin-right: auto;
        
        padding-right: 80px;
        display: block;
        width: 1055px;
    }
 
    .left {
        width: 475px;
        height: 475px;
        padding: 0px 0px 10px 0px;
        float: left;
        display: block;
    }
 
    .right {
        width: 420px;
        float: right;
        display: block;
        background: #FFF;
    }
 
	    .copyright_login {
        float: right;
        font-size: 12px;
        color: #702789;
        padding: 4px 0px 0px 0px;
    }
</style>

   {!! Form::open(['route' => 'ventas.cliente.store', 'method' => 'POST']) !!}
	<div class="row">
		<div id="Div1" class="MainArea">
			<div class="left">
				<div class="left_img">
					<img src="/imagenes/frontend/register/logo_right.jpg" alt="">
				</div>
			</div>	
			
			<div class="right">
				
					<!--Contenido-->
					@include('frontend.register.partials.fields')
				
			</div>
			
			<div class="for text-center">
				{!! Form::submit('Registrar', ['class'=> 'btn btn-primary']) !!}
				<a class="btn btn-danger" href="{{ route('ventas.cliente.index')}}">
					Cancelar22
				</a>
			</div>
				 
		</div>
	</div>
     
     {!! Form::close() !!}

@push ('scripts')
<script>
     
</script>
@endpush

@endsection

@section('js')
    <script>
        $(".inputmask1").inputmask("(999) 9999999");
        $(".inputmask2").inputmask("(999) 999999999");  

        $('.datepicker').datepicker({
            format: "dd-mm-yyyy",
            language: "es",
            autoclose: true
        });
         
    //Para activacion de textarea mediante checkbox
        function showContent() {
            element = document.getElementById("content");
            check = document.getElementById("check");
            if (check.checked) {
                element.style.display = 'block';
            }
            else {
                element.style.display = 'none';
            }
        }

    </script>
@endsection