app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
 

Route::get('/', function () {
    return view('auth/login');
});


//RUTA PARA LA GUARDAR FOTOS DEL VEHICULO  
Route::resource('fotocar','FotoCarController');

Route::post('/subir/{id}/{placa}/{cliente}', 'FotoCarController@subir')->name('fotocar.subir');

Route::get('/acerca', function () {
    return view('acerca');
});
 
 
/*LOGIN // NUEVO CLIENTE FRONTEND*/
//Route::get('ventas/creacion', 'Ventas2Controller@create')->name('ventas.create');
Route::get('front/nuevo-cliente', 'FrontEndController@create')->name('nuevo.cliente');
Route::post('/store/sales', 'SalesOrderController@store');

//FIN LOGIN
 
// 

//MODULO DE GESTION DE CITAS ATENCION VEHICULAR
 
/*Ruta para guardar la recepcion de cita */
Route::resource('appointment/receipt','AppointmentController@receipt_cita');
 
 
Route::get('mkt/{cita_id}/pdf', 'AppointmentController@cita_cliente')->name('cita_customer');
 
//FIN MODULO GESTION DE CITAS ATENCION VEHICULAR

// 
//ASESOR : RECEPCION
//Route::resource('asesor/inventario','RecepcionAsesorController');
 
  
Route::auth();

   

/**--------- reportes */
 


// ----------------------------------------------------------------------------------


//FIN RECEPCION OC

 
//fin PARAMETROS  DE SUCURSAL


// Inicio Seguridad-Sucursal
  
//++INICIO RECEPCIONES
 
//FIN RECEPCIONES

 
/*** RUTAS PARA COTIZACIÓN*/
 

//Vehiculos - RT 
//FIN Tipo de Transacciones
 
//FIN TRX VARIAS
 
// FIN ITEM-MMA

//IMPORTACION DE REGISTROS
 
//FIN //IMPORTACION DE REGISTROS


// organizacion

Route::get('/home', 'HomeController@index');
 
Route::get('/home', 'HomeController@index');


// fndlookup 
 
// labor
 
Route::get('/{slug?}', 'HomeController@index');
 
//CREACION AUTOMATICA DE ORDEN DE TRABAJO
Route::resource('asesor/vehiculo','VehiculoController');


Route::resource('ventas/cliente','ClienteController');
 
Route::resource('seguridad/usuario','UsuarioController');
 
Route::resource('appointment/receipt','AppointmentController@receipt_cita');

Route::get('/subir', function(){
	return "hola mundo";
});



  

app/Appointment.php
<?php

namespace sisVentas;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Collection;
use Carbon\Carbon;

class Appointment extends Model
{

    protected $table = "mkt_reservations";

    protected $fillable = [  
  	   'id', 'numcita',
  	   'placa_id', 
  	   'customer_id',
       'date_reservation',
       'datetime_reservation',
       'site_id',
       'confirmed',
       'service1_id',
       'service2_id',
       'comments',
       'status',
        'updated_at',
       'last_updated_by',         
       'created_by',
       'created_at', 
         
	   ];

      public function attachedDocuments()
    {
      return $this->hasMany(FndAttachedDocuments::class, 'pk1_value');
    }
    
        public function sucursal()
    {
        return $this->hasOne(Site::class,'id','site_id');
    }
    
    public function cliente()
    {
        return $this->belongsTo('sisVentas\Cliente', 'customer_id', 'idcliente');
    }

    public function servicio1()
    {
        return $this->belongsTo('sisVentas\Labor', 'service2_id', 'idlabor');
    }


    public function servicio2()
    {
        return $this->belongsTo('sisVentas\Labor', 'service1_id', 'idlabor');
    }


  public function vehiculo()
    {
        return $this->hasOne(Vehiculo::class,'id','placa_id');
    }

   

    public function marca()
    {
        return $this->belongsTo('sisVentas\Marca', 'idmarca', 'idmarca');
    }

    public function user()
    {
        return $this->belongsTo('sisVentas\User', 'last_updated_by');
    }

    public function createby()
    {
        return $this->belongsTo('sisVentas\User', 'created_by');
    }
 
    
}

app/Http/Controllers/AppointmentController.php
<?php

namespace sisVentas\Http\Controllers;

use Illuminate\Http\Request;
use sisVentas\Http\Requests\VehiculoFormRequest;
use sisVentas\Vehiculo;
use sisVentas\Appointment;
use sisVentas\User;
use sisVentas\createby;
use sisVentas\FndLookup;
use Illuminate\Support\Facades\Session; 
use sisVentas\Site;
use sisVentas\Labor;
use Carbon\Carbon;
use sisVentas\Cliente;
use sisVentas\FndAttachedDocuments; 
use Laracasts\Flash\Flash;
use sisVentas\Http\Requests;
 
use Maatwebsite\Excel\Facades\Excel;
use DB;
use Illuminate\Support\Facades\Auth;

class AppointmentController extends Controller
{


        public function receipt_cita()

    {     
         $datos = Appointment::where('status','<>','Anulado')->with('cliente')->orderBy('id', 'DESC')->get();
        return view('appointment.receipt.index')->with('datos', $datos);

    }


        public function cita_cliente($cita_id)

    {     
        $d = Appointment::where('id',$cita_id)->first();
  
        return \PDF::loadView('appointment.register.pdfs.appointmentCust', compact('d'))->setpaper('a4')->stream(); 

    }

  //historial de cotizaciones
   public function historial()

    {   
        
        $labores = labor::select('nombrelabor', 'idlabor')->where('condicion','=',1)->orderBy('nombrelabor', 'ASC')->get(); 

        $vehiculos = Vehiculo::select('placa', 'id')->where('no_atender','=',0)->orderBy('placa', 'ASC')->get(); 
        $clientes = Cliente::select('full_name', 'idcliente')->where('no_atender','=', 0)->orderBy('full_name', 'ASC')->get();
        $sucursales = Site::select('name', 'id')->where('condicion','=', 1)->orderBy('name', 'ASC')->get();

  
        return view('appointment.register.filters')->with('labores',$labores)
                                            ->with('vehiculos',$vehiculos)
                                            ->with('clientes',$clientes)
                                            ->with('sucursales',$sucursales)
                                            ;

    }

    public function export(Request $request)
    {   
        $mytime = Carbon::now()->format('d.m.Y H-i');
        $varname =  $mytime;
        $pfilename = 'Parte de Servicios_' .$varname ;

        Excel::create($pfilename, function($excel) {
            $excel->sheet('listado', function($sheet) {
                 $vehiculos = PartService::orderBy('id', 'desc')->get();
                $sheet->loadView('mortuary.service.excel.export')->with('arrdatos', $vehiculos);
            });
        })->export('xls');
    }

    public function index()
    {
        $datos = Appointment::with('cliente')->orderBy('id', 'DESC')->get();
        return view('appointment.register.index')->with('datos', $datos);
    }


    public function create()
    {
        $date = Carbon::now()->format('Y-m-d');

        $operacion = 'Create';

        $labores = Labor::select('nombrelabor', 'idlabor')->where('condicion','=',1)->orderBy('nombrelabor', 'ASC')->get(); 

        $vehiculos = Vehiculo::select('placa', 'id')->where('no_atender','=',0)->orderBy('placa', 'ASC')->get(); 
        $clientes = Cliente::select('full_name', 'idcliente')->where('no_atender','=', 0)->orderBy('full_name', 'ASC')->get();
        $sucursales = Site::select('name', 'id')->where('condicion','=', 1)->orderBy('name', 'ASC')->get();

        
        return view('appointment.register.create')->with('sucursales', $sucursales)->with('clientes', $clientes)->with('vehiculos', $vehiculos)->with('labores', $labores)->with('operacion', $operacion);
    }
    
    /**
     * Function to save PartService
     */
    public function save_service(Request $request) 
    {
        
        if ($request->action == 'Nuevo') {
            $service = new Appointment();

        } else {
            $service = Appointment::findOrFail($request->id);
        }
        
      
        $service->site_id =  $request->site_id;
        $service->placa_id = $request->placa_id;
        $service->status = "Nuevo";
         
        $service->customer_id = $request->customer_id;
        $service->datetime_reservation = $request->datetime_reservation;

        $service->service1_id = $request->service1_id;
        $service->service2_id = $request->service2_id;
        $service->comments = $request->comments;
        
        $service->confirmed = 'N';
        
        $service->created_by =  Auth()->user()->id;
        $service->last_updated_by =  Auth()->user()->id;
        
     //   dd( $service);

        if ($service->save()) {
           if ($request->action == 'Nuevo') {
                Flash::success("Se ha registrado de manera exitosa!")->important();
           } 
           else 
            {   
                //INICIO ATTACH DOCUMENT 
                if ($request->hasFile('file')) 
                {
                    $idrecord = $service->id;
                    $numrecod = $service->numpart; 
                    $entity_name = 'Mort_PartService';
                    //dd($purchaseOrder->site_id)  ;
                  $files = $request->file('file');
                 // dd($files);
                  foreach($files as $file) {
                    $documento = $service->site_id."_".$numrecod."_".$file->getClientOriginalName();
                    $destination = base_path() . '/public/documents/PartService';
                    try {
                      $file->move($destination, $documento);
                    } catch (\Exception $e) {
                      // dd('paso1');
                      DB::rollback();
                    }
                    try {
                      $saveFile = FndAttachedDocuments::create([
                                                                'pk1_value' => $idrecord,
                                                                'path_file' => $destination.'/'.$documento,
                                                                'description' => $request->description_adjunto,
                                                                'entity_name' => $entity_name ,
                                                                'name_file' => $documento,
                                                                'created_by' => Auth::user()->id,
                                                                'last_updated_by' => Auth::user()->id,
                                                              ]);
                    } catch (\Exception $e) {
                      // dd($e);
                      DB::rollback();
                    }
                  }//fin foreach
                } //fin if
               

                DB::commit();
                //FIN ATTACHD DOCUMENT        
                    

                Flash::success("Se ha actualizado de manera exitosa!")->important();
            }           
           return redirect('appointment/servicio');//->route('mortuary.service.index');
        }
    }

    /**
     * Function to view edit
     */
    public function edit($id) {
        $service = PartService::findOrFail($id);
        if ($service) {
            $date = Carbon::now()->format('Y-m-d');
            $tipomov =  FndLookup::where('lookup_type', 'MOVILIDAD_FUNERAL')->first();
            $tipomov = (isset($tipomov) ? $tipomov->fndLookupValue->pluck('description', 'idlvalue')->toArray() : []);
    
            $tipodes =  FndLookup::where('lookup_type', 'TIPO_DESPACHO_FUNERARIA')->first();
            $tipodes = (isset($tipodes) ? $tipodes->fndLookupValue->pluck('description', 'idlvalue')->toArray() : []);

            $capilla =  FndLookup::where('lookup_type', 'CAPILLA_FUNERAL')->first();
                
            $capilla = (isset($capilla) ? $capilla->fndLookupValue->pluck('description', 'idlvalue')->toArray() : []); 

    
            $modelocap =  FndLookup::where('lookup_type', 'MODELO_CAPILLA_FUNERAL')->first();
            $modelocap = (isset($modelocap) ? $modelocap->fndLookupValue->pluck('description', 'idlvalue')->toArray() : []);        
           
            $clientes = Cliente::orderBy('full_name', 'ASC')->where('effective_end_date', '>=', $date)->lists('full_name', 'idcliente');

            $cementerio = Cementerio::orderBy('nombre', 'ASC')->where('condicion', '=', 1)->lists('nombre', 'id');

            $operacion = 'Edit';
            
            return view('mortuary.service.edit')->with('service', $service)->with('clientes', $clientes)->with('cementerio', $cementerio)->with('capilla', $capilla)->with('modelocap', $modelocap)->with('operacion', $operacion)->with('tipodes', $tipodes)->with('tipomov', $tipomov);;
        }
    }

    /**
     * Function to delete service
     * @param {id} Id del renglon
     */
    public function delete_service(Request $request) {
        $id = $request->id;
        $service = Appointment::findOrFail($id);
        $result = array();
        if ($service) {
            $service->status = "Anulado";
            $service->updated_at = Carbon::now();
            $service->last_updated_by = Auth()->user()->id;
            if ($service->save()) {
                //Flash::success("Se ha anulado el registro de manera exitosa!")->important();
                //return redirect('funeraria/servicio');
                $result = array(
                    "status" => 1,
                    "type" => "success",
                    "message" => "Se ha anulado el registro de manera exitosa!"
                );
            } else {
                $result = array(
                    "status" => 0,
                    "type" => "error",
                    "message" => "No se pudo anular el registro, intenta mas tarde!"
                );
            }
        } else {
            $result = array(
                "status" => 0,
                "type" => "warning",
                "message" => "No se encontro el registro a anular, favor de verificar!"
            );
        }
        return response()->json($result);
    }

resources/views/appointment/receipt/SeleccionaCamara.blade.php
@extends('layouts.admin')

@section('title', 'Listado de Sucursal')

@section('contenido')

      <form action="{{ route('fotocar.edit',$id) }}">
        <h1 class="bg-success">SELECCIONA EL MEDIO DE CAMARA</h1>
       <select class="form-control" name="camara">
         <option>Selecciona tu Camara</option>
          <option value="frontal">Frontal</option>
          <option value="posterior">Posterior</option>
       </select>
       <br>
       <button class="btn btn-info">Enviar informacion</button>
      </form>

	
   
@endsection

@section('js')

	
@endsection

resources/views/appointment/receipt/create.blade.php
@extends('layouts.admin')
@section('title', 'Registro de Servicios')
@section('contenido')
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header with-border">                   
				<h3 class="box-title">Nueva Cita de Servicio</h3>
			</div>
		  
			{!!Form::open(array('url'=>'appointment/servicio/save','method'=>'POST','autocomplete'=>'off' , 'enctype' => 'multipart/form-data','files'=>'true'))!!}
			{{Form::token()}}
			<input type="hidden" name="action" value="Nuevo">
			<div class="box-body">
				<div class="nav-tabs-custom"> 
					<ul class="nav nav-tabs">
						<li class="active">
							<a href="#tab_1" data-toggle="tab">INF. GENERAL</a>
						</li>
						<!--
						<li>
							<a href="#tab_2" data-toggle="tab">INF. COMPLEMENTARIA</a>
						</li>
						<li>
							<a href="#tab_3" data-toggle="tab">DATOS DE APROBACION</a>
						</li>
						
						<li>
							<a href="#tab_4" data-toggle="tab">ADJUNTOS</a>
						</li>	
					-->						
					</ul>
					<div class="tab-content">
						<div class="tab-pane active" id="tab_1">								 
							<div class="row">
								<div class="col-md-12">									 
									<!--Contenido-->
									@include('appointment.register.partials.fields')									  
								</div> 									
							</div>								 
						</div>
						 
						<!-- inicio de adjuntos-->

						<div class="tab-pane fade" id="tab_4" >

							<div class="row">
				 
								<div class="col-md-4">
									<div class="form-group">

										{!! Form::label('description_adjunto', 'DESCRIPCION') !!}

										{!! Form::textarea('description_adjunto', null, ['class' => 'form-control', 'size' => '30x2', 'placeholder' => '']) !!}

									</div>

									<div class="form-group">
										{!! Form::label('file', 'Agregar Adjunto') !!}
										{!! Form::file('file[]',null, ['class' => 'form-control', 'placeholder' => '', '']) !!}
										<button class="add_more">Agregar otro Archivo</button>
									</div>
									@if ($errors->has('file'))
									<span style="color:red">{{ $errors->first('file') }}</span>
									@endif
								</div>
								<div class="col-md-8">
									@if ($operacion == 'Create')
										Grabe la informacion antes de adjuntar archivos
									@else
									  
										@foreach($purchaseOrder->attachedDocuments as $doc)
											<div class="col-md-2">
												<div class="">
												<a href="{{ url('documents/'.$doc->name_file) }}" download>
													<i style="font-size: 6em;" class="fa fa-file-text-o"></i>
												</a>
												</div>
												<div class="" style="height: 50px">
												{{ $doc->name_file }}
												</div>
												<div class="">
												<a class="btn btn-danger" href="{{ url('orden/eliminar/documento/'.$doc->attached_document_id) }}">
													Eliminar
												</a>
												</div>
											</div>
										@endforeach
									@endif
								</div>
				 

							</div>


						</div>

						<!-- FIN de adjuntos-->					 
					</div>
				</div>
			</div>
			<div class="box-footer pull-right">
				{!! Form::submit('Registrar', ['class'=> 'btn btn-primary']) !!}
				<a class="btn btn-danger" href="">
					Cancelar
				</a>
			</div>
			{!!Form::close()!!}	
		</div>
	</div>
</div>	
@endsection

@section('js')
<script>
	//SElECT CON FILTRO
        $(document).ready(function() {
        $(".select2").select2();
        });

        //datepicker
        $('.datepicker').datepicker({
            format: "dd-mm-yyyy",
            language: "es",
            autoclose: true
        });
		
		$(window).load(function(){
			// PROCESO PARA CARGAR VISTA PREVIA DE IMAGE SUCURSAL
			 $(function() {
					  $('#path_image_logo').change(function(e) {
					      addImage(e); 
					     });

				     function addImage(e){
				      var file = e.target.files[0],
				      imageType = /image.*/;
				    
				      if (!file.type.match(imageType))
				       return;
				  
				      var reader = new FileReader();
				      reader.onload = fileOnload;
				      reader.readAsDataURL(file);
				     }
			  
				     function fileOnload(e) {
				      var result=e.target.result;
				      $('#imgSalida').attr("src",result);
				     }

			    });
	  	});

</script>
@endsection
 

resources/views/appointment/receipt/edit.blade.php
@extends('layouts.admin')
@section('title', 'Editar Servicio')
@section('contenido')
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header with-border">                   
				<h3 class="box-title">Editar Parte de Servicio</h3>
			</div>
			{!!Form::open(array('url'=>'/funeraria/servicio/save','method'=>'POST','autocomplete'=>'off' , 'enctype' => 'multipart/form-data','files'=>'true' ))!!}
			{{Form::token()}}
			<input type="hidden" name="action" value="Editar">
			<input type="hidden" name="id" value="{{$service->id}}">			
			<div class="box-body">
				<div class="nav-tabs-custom"> 
					<ul class="nav nav-tabs">
						<li class="active">
							<a href="#tab_1" data-toggle="tab">INF. GENERAL</a>
						</li>
						<li>
							<a href="#tab_2" data-toggle="tab">INF. COMPLEMENTARIA</a>
						</li>
						<li>
							<a href="#tab_3" data-toggle="tab">DATOS DE APROBACION</a>
						</li>
						<li>
							<a href="#tab_4" data-toggle="tab">ADJUNTOS</a>
						</li>							 
					</ul>
					<div class="tab-content">
						<div class="tab-pane active" id="tab_1">								 
							<div class="row">
								<div class="col-md-12">									 
									<!--Contenido-->
									@include('mortuary.service.partials.fields')									  
								</div> 									
							</div>								 
						</div>
						<div class="tab-pane" id="tab_2">								 
							<div class="row">
								<div class="col-md-12">
									<!--Contenido-->									
									@include('mortuary.service.partials.complemtos')							
								</div>              
							</div>								 
						</div>							
						<div class="tab-pane" id="tab_3">								 
							<div class="row">
								<div class="col-md-12">
									<!--Contenido-->									
										@include('mortuary.service.partials.aprobacion') 																	 
								</div>              
							</div>								 
						</div>
						<!-- inicio de adjuntos-->

						<div class="tab-pane fade" id="tab_4" >

							<div class="row">
				 
								<div class="col-md-4">
									<div class="form-group">

										{!! Form::label('description_adjunto', 'DESCRIPCION') !!}

										{!! Form::textarea('description_adjunto', null, ['class' => 'form-control', 'size' => '30x2', 'placeholder' => '']) !!}

									</div>

									<div class="form-group">
										{!! Form::label('file', 'Agregar Adjunto') !!}
										{!! Form::file('file[]',null, ['class' => 'form-control', 'placeholder' => '', '']) !!}
										<button class="add_more">Agregar otro Archivo</button>
									</div>
									@if ($errors->has('file'))
									<span style="color:red">{{ $errors->first('file') }}</span>
									@endif
								</div>
								<div class="col-md-8">
									@if ($operacion == 'Create')
										Grabe la informacion antes de adjuntar archivos
									@else
									  
										@foreach($service->attachedDocuments as $doc)
											<div class="col-md-2">
												<div class="">
												<a href="{{ url('documents/'.$doc->name_file) }}" download>
													<i style="font-size: 6em;" class="fa fa-file-text-o"></i>
												</a>
												</div>
												<div class="" style="height: 50px">
												{{ $doc->name_file }}
												</div>
												<div class="">
												<a class="btn btn-danger" href="{{ url('parteserv/eliminar/documento/'.$doc->attached_document_id) }}">
													Eliminar
												</a>
												</div>
											</div>
										@endforeach
									@endif
								</div>
				 

							</div>


						</div>

						<!-- FIN de adjuntos-->						 
					</div>
				</div>
			</div>
			<div class="box-footer pull-right">
				{!! Form::submit('Registrar', ['class'=> 'btn btn-primary']) !!}
				<a class="btn btn-danger" href="">
					Cancelar
				</a>
			</div>
			{!!Form::close()!!}	
		</div>
	</div>
</div>	
@endsection

@push ('scripts')
<script type="text/javascript" charset="utf-8" async defer>
$(document).ready(function(){
    $('.add_more').click(function(e){
        e.preventDefault();
        $(this).before("<input name='file[]' type='file' class='form-control'/>");
    });
});
</script>
@endpush
 

resources/views/appointment/receipt/index.blade.php
@extends('layouts.admin')

@section('title', 'Listado de Sucursal')

@section('contenido')
    <div class="box">
        @include('util.success')
        <div class="box-header with-border">
            <h3 class="box-title">
                Listado de Citas para Recepcionar
            </h3>
            <div class="box-tools">
				<div class="text-center">
                      
                </div>	
				                    
            </div>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box-body table-responsive_ no-padding">
                        <table class="table table-hover display_ table-responsive table-condensed" id="table">
                            <thead>
                            <tr> 
                                <th>CLIENTE</th>
								<th>PLACA</th>
								 
								<th>FEC. CITA</th>
 								<th>ESTADO</th> 
                                <th>ACCIONES</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($datos as $var)
								@php
                                    $fsistema = date('Y-m-d');
                                    $ftermino = date($var->datetime_reservation);
                                    $datetime1 = date_create($fsistema);
                                    $datetime2 = date_create($ftermino);
                                     
                                @endphp
                                @if($datetime2 == $datetime1)
                                    <!-- rojo -->
                                    <tr style="color: #E21C1F;">
                                    
                                @else 
                                    <tr>
                                @endif
								 
									<td>  {{ $var->cliente->full_name }} </td>
									<td> {{ $var->vehiculo->placa }} </td>
 									<td> {{ $var->datetime_reservation }} </td>
									<td> <span class="success">{{ $var->status }}</span> </td>									  
                                    <td>                                        
                                        @if ($var->status != "Anulado")
                                        
                                         <a href="{{ route('fotocar.show', $var->id) }}"  ><i class="fa fa-file" aria-hidden="true"></i>
											 
										</a>
										@endif
									 
										
										<a href="{{ route('cita_customer', [$var->id]) }}"
                                            target="_blank">
                                            <i class="fa fa-print" aria-hidden="true"   ></i>
                                        </a>
										
                                    </td>
 
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>
        <!-- /.box -->
    </div>
@endsection

@section('js')
    <!-- SweetAlert 2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#table').DataTable({
                "order": [[ 1, "desc" ]],
                "language": {
                    "url": "{{ asset('AdminLTE/plugins/datatables/esp.lang') }}"
                }
            });
            
            //Promesa para anular el registro
            const _delete = function (id) {
                return new Promise( (resolve, reject) => {
                    $.ajax({
                        url: '/appointment/servicio/delete',
                        method: 'post',
                        dataType: 'json',
                        headers: {
                            "X-CSRF-TOKEN": $('meta[name="csrf-token"]').attr("content")
                        },
                        data: {id: id},
                    }).done(resolve).fail(reject);
                });
            }

            $('.delete_service').on('click', function (e) {
                e.preventDefault();
                let _id = $(this).data('id');                
                Swal.fire({
                    title: 'Estas seguro de anular el registro?',
                    text: "¡No podrás revertir esto!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Si, anular!',
                    cancelButtonText: 'Cancelar',
                    }).then((result) => {
                    if (result.value) {                       
                        _delete(_id).then(result => {
                            if (result.status) {
                                Swal.fire({
                                    title: 'Anulado!',
                                    text: result.message,
                                    icon: 'success'
                                }).then( () => {
                                    location.reload();
                                });
                            } else {
                                Swal.fire({
                                    title: 'Detalle encontrado!',
                                    text: result.message,
                                    icon: result.type
                                }); 
                            }
                        }).catch(error => {
                            console.log(error)
                        });
                    }
                });
            })
        });
    </script>
@endsection

resources/views/appointment/receipt/upload-page.blade.php
<?php 

for($i=1; $i < count($_POST); $i++){
 
 ?>
 <table border="1">
   <tr>
    <th>Cliente</th>
     <th>Imagenes  </th>
     <th></th>
   </tr>
   <tr>
    <td>Cliente juan</td>
     <td> <img src="destino/<?php echo $valor?>/imagen<?php echo $i ?>.png" alt="" width="80"></td>
   </tr>
 </table>

 <?php

}

?>